### ISSUE TITLE
Busyboxy / ash support

### ISSUE THREAD

**Issue by slthomason** [dominictarr/JSON.sh#13]
Hi there,

I am very interested in using JSON.sh. However, I am having a problem when running it on OpenWRT --> a distro that uses Busybox / ash (not bash).

I added this at the top of the file:
# !/bin/sh

But when I try to run it, I get this:
# ./JSON.sh

sh: =: argument expected

Any ideas?  Please advise?  Thanks!

**Comment by Shkeats** [comment]
@slthomason or @dominictarr  Could you post back your working modified JSON.sh file for BusyBox Ash? I've read through the whole thread here but It's a little unclear as to which of the ideas and advice you followed/applied to get this working.

**Comment by dominictarr** [comment]
@Shkeats since you reminded me of this thread, it would be pretty awesome to get this really crossplatform, but to do that realistically either we can painstakingly maintain it (nope) or maybe we could get cross platform integration tests? we can easily run tests on travis ci, which runs on ubuntu, so if we can install the different bashes on ubuntu, we can run the tests on each one on travis, and then we'll know if a pull request breaks anything.

**Comment by aidanhs** [comment]
@dominictarr I'll have a play with drone.io and possibly make a PR - because it's in docker we could easily check a few different shell and distro combinations e.g. busybox+ash, ubuntu+dash/bash/zsh.

**Comment by aidanhs** [comment]
Turns out drone doesn't have a publicly hosted instance, so travis it is.

@Shkeats see #43, I've fixed a couple of bashisms and made all the tests work on a busybox docker image. Can you see if that branch works?

**Comment by dominictarr** [comment]
@aidanhs I recall that travis uses docker if you set `usesudo: false` (or something like that) in the config.

**Comment by Shkeats** [comment]
@aidanhs Thanks so much for this, it's great. I've deployed it on a dd-wrt router that has a very old build of BusyBox and it seems to work as expected. At least it runs and outputs parsed json. I've yet to test against a complex use case but will let you know if I run into any issues.
